### ISSUE TITLE
laminas/laminas-crypt:^3.4 provoques Exception

### ISSUE THREAD

**Issue by ThibaultPelloquin** [laminas/laminas-di#88] opened 2023-03-16 10:31 UTC
### Bug Report

Installing on Symfony 6.2 project with PHP 8.1

|    Q        |   A
|------------ | ------
| Version(s)  | 3.0.6

#### Summary

Get this Exception :

PHP Fatal error:  Declaration of Laminas......::has($name) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /path/info line int

Same as described here: https://github.com/laminas/laminas-di/issues/78

#### Expected behavior

Solution: replace laminas/laminas-crypt:^3.4 by laminas/laminas-crypt:^3.10 where bug has been fixed.

**Comment by Ocramius** [comment] 2023-03-16 10:40
`laminas/laminas-crypt:^3.10` is included in the `laminas/laminas-crypt:^3.4` range. 

Are you running `composer update --ignore-platform-reqs`, perhaps? Because `laminas/laminas-crypt:3.4.0` does **NOT** support `php:8.1.*`:

https://github.com/laminas/laminas-crypt/blob/a058eeb2fe57824b958ac56753faff790a649e18/composer.json#L22

**Comment by Ocramius** [comment] 2023-03-16 10:42
Closing here: root cause is not a link with `laminas/laminas-crypt`, since a dependency upgrade would on your end would already show that :-) 

Please re-open after making sure you are on the latest dependencies.

**Closed as completed by Ocramius** 2023-03-16 10:42 UTC
Labels: Bug, Invalid
